services:
  web-app:
    build: backend
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ../.env
    command: >
      sh -c "
            python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py createsuperuser --noinput &&
            python manage.py runserver 0.0.0.0:8000"
