# Generated by Django 5.1.6 on 2025-03-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('temperature', models.FloatField(help_text='Temperature (°C)')),
                ('feels_like', models.FloatField(help_text='Feels-like temperature (°C)')),
                ('humidity', models.IntegerField(help_text='Relative humidity (%)')),
                ('pressure', models.FloatField(help_text='Atmospheric pressure (mbar)')),
                ('wind_speed', models.FloatField(help_text='Wind speed (km/h)')),
                ('wind_gust', models.FloatField(blank=True, help_text='Wind gusts (km/h)', null=True)),
                ('wind_direction', models.CharField(help_text='Wind direction (ENE, N, SW, etc.)', max_length=10)),
                ('wind_degree', models.IntegerField(help_text='Wind direction in degrees (0° - North, 90° - East)')),
                ('cloudiness', models.IntegerField(help_text='Cloud cover (%)')),
                ('visibility', models.FloatField(help_text='Visibility (km)')),
                ('precipitation', models.FloatField(default=0.0, help_text='Precipitation amount (mm)')),
                ('uv_index', models.FloatField(help_text='UV index (sun exposure risk)')),
                ('dew_point', models.FloatField(help_text='Dew point (°C)')),
                ('weather_condition', models.CharField(help_text='Description of current weather conditions (Clear, Rain, Fog, etc.)', max_length=100)),
                ('weather_icon', models.URLField(help_text='URL of the weather condition icon')),
            ],
        ),
    ]
